emxevents/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('events.urls'), name='events_urls'),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

events/urls.py
from . import views
from django.urls import path
from .views import OldEventList, DeleteSignUp, EditSignUp


urlpatterns = [
    # Home page displaying the list of upcoming events
    path('', views.EventList.as_view(), name='home'),

    # Page displaying the list of past events
    path('old-events/', OldEventList.as_view(), name='old_events'),

    # Detail page for a specific event identified by its slug
    path('<slug:slug>/', views.EventDetail.as_view(), name='event_detail'),

    # Like/unlike an event
    path('like/<slug:slug>', views.EventLike.as_view(), name='event_like'),

    # Edit a sign-up for event
    path('event/<slug:slug>/edit_signup/<int:signup_id>/',
         EditSignUp.as_view(), name='edit_signup'),

    # Delete a sign-up from event
    path('event/<slug:slug>/delete_signup/<int:signup_id>/',
         DeleteSignUp.as_view(), name='delete_signup'),
]

events/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

STATUS = ((0, "Draft"), (1, "Active"))


# Event model to create events
class Event(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="emx_events"
    )
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    featured_image = CloudinaryField('image', default='placeholder')
    excerpt = models.TextField(blank=True)
    event_date = models.DateField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    likes = models.ManyToManyField(
        User, related_name='event_likes', blank=True
    )

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

    @property
    def number_of_likes(self):
        return self.likes.count()


# SignUp model to use when signing up participants to event.
class SignUp(models.Model):
    sign = models.ForeignKey(
        Event, on_delete=models.CASCADE, related_name='signed_up'
    )
    name = models.CharField(max_length=80)
    first_name = models.CharField(max_length=80)
    last_name = models.CharField(max_length=80)
    email = models.EmailField()
    start_number = models.CharField(
        max_length=8,
        blank=True,
        null=True
    )
    transponder = models.IntegerField(null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return f"{self.name}, signed up {self.created_on}"

templates/base.html
{% load static %}

<!DOCTYPE html>

<html class="h-100" lang="en">
    <head>
        <title>EMX Events</title>

        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
        </script>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>

    <body class="d-flex flex-column h-100 main-bg">

        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-white">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'home' %}">
                    <span class="brand">
                        <span class="blue-e">E</span><span class="brown-mx">MX</span><span class="thin">|Event</span>
                    </span>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                    aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarText">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'old_events' %}">Old Events</a>
                        </li>
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                            </li>
                            {% if user.is_staff %}
                            <li>
                                <a class="nav-link" href="{% url 'admin:events_event_add' %}" target="_blank">Add Event</a>
                            </li>
                            {% endif %}
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                        </li>
                        {% endif %}                    
                    </ul>
                </div>
            </div>
        </nav>

        <!-- Info area-->
        <div class="info-area">
            <div class="container-fluid">
                {% if user.is_authenticated %}
                    {% if user.is_staff %}
                    <p class="logged-in-text">Logged in as:<br><a href="{% url 'admin:index' %}" target="_blank"><strong>{{ user.username }}</strong></a>
                    </p>
                    {% else %}
                    <p class="logged-in-text">Logged in as:<br><strong>{{ user.username }}</strong></p>
                    {% endif %}
                {% endif %}
            </div>
        </div>

        <!-- Message notifications -->
        <div class="container">
            <div class="row">
                <div class="col-md-8 offset-md-2">
                    <sdiv class="message-bar">
                        {% for message in messages %}
                        <p class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
                            {{ message | safe }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </p>
                        {% endfor %}
                    </span>
                </div>
            </div>
        </div>

        
        
        <!-- Main -->
        <main class="flex-shrink-0 main-bg main-padding">
            {% block content %}
            <!-- Content goes here -->
            {% endblock content %}
        </main>

        <!-- Footer -->
        <footer class="footer mt-auto py-3 emx-bg">
            <p class="m-0 text-center text-white">Events for enduro and Motocross</p>
            <p class="m-0 text-center text-white">External sites: 
                <a href="https://www.facebook.com/RobstarRacing" target="_blank"><i class="fab fa-facebook-square ms-3"></i></a>
                <a href="https://www.instagram.com/robstarracing/" target="_blank"><i class="fab fa-instagram-square ms-3"></i></a>
                <a href="https://www.youtube.com/@robertahlin1600" target="_blank"><i class="fab fa-youtube-square ms-3"></i></a>
                <a href="https://live.emx-timing.se/" target="_blank"><i class="far fa-clock ms-3"></i></a>
            </p>
        </footer>
        <script>
            setTimeout(function() {
                let messages = document.getElementById('msg');
                let alert = new bootstrap.Alert(messages);
                alert.close();
            }, 10000);
        </script>
    </body>
</html>

templates/edit_signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}


<div class="container">
    <div class="row">
        <div class="col card mb-4 mt-3 left top">
            <div class="card-body">
                <h3>Edit Sign Up</h3>
                <hr>
                <form method="post" action="{% url 'edit_signup' slug=slug signup_id=signup_id %}">
                    {% csrf_token %}
                    <!-- Fields for first name and last name -->
                    <p>Name: {{ form.first_name }}{{ form.last_name }}</p>
                    <!-- Start number (not editable) -->
                    <p>Start Number: <strong>{{ form.instance.start_number }}</strong></p>
                    <!-- Fields for transponder number -->
                    <p>Transponder no.: {{ form.transponder }}</p>
                    <button class="btn btn-signup btn-lg" onclick="goBack()">Cancel</button>
                    <button type="submit" class="btn btn-signup btn-lg">Save Changes</button>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    function goBack() {
        window.history.back();
    }
</script>
{% endblock %}

templates/event_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load crispy_forms_tags %}
{% now "Y-m-d" as today %}

<div class="masthead">
    <div class="container">
        <div class="row">
            <div class="col-md-6 masthead-text">
                <!-- Event title -->
                <h1 class="post-title">{{ event.title }}</h1>
                <!-- Show scheduled event date, author and the events's created date. -->
                <p class="post-subtitle">Event date: <strong>{{event.event_date}}</strong><i> created by:
                        {{event.author}} on {{ event.created_on }}</i></p>
            </div>
            <div class="d-none d-md-block col-md-6 masthead-image">
                <!-- The featured image URL goes in the src attribute -->
                {% if "placeholder" in event.featured_image.url %}
                <img class="card-img-top" src="{% static 'images/emx.webp' %}" alt="dirtbike rider revving away">
                {% else %}
                <img class="card-img-top" src="{{ event.featured_image.url }}" alt="Uploaded image for the event">
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col card mb-4 mt-3 left top">
            <div class="card-body">
                <!-- The event content inside the card-text. -->
                <p class="card-text ">{{event.content | safe}}</p>
                <div class="row">
                    <div class="col-1">
                        
                            {% if user.is_authenticated %}
                            <form class="d-inline" action="{% url 'event_like' event.slug %}" method="POST">
                                {% csrf_token %}
                                {% if liked %}
                                <button type="submit" name="emxevent_id" value="{{ event.slug }}" class="btn-like">
                                    <i class="fas fa-heart"></i>
                                </button>
                                {% else %}
                                <button type="submit" name="emxevent_id" value="{{ event.slug }}" class="btn-like">
                                    <i class="far fa-heart"></i>
                                </button>
                                {% endif %}
                            </form>
                            {% else %}
                            <span class="text-secondary">
                                <i class="far fa-heart"></i>
                            </span>
                            {% endif %}
                            <strong>
                            <span class="text-secondary">
                                {{event.number_of_likes}}
                            </span>
                            </strong>
                    </div>
                    <!-- View how many approved sign ups and total sign ups -->
                    <div class="col-3">
                        {% with signed_up.count as total_signed_ups %}
                        <strong class="text-secondary">
                            <i class="far fa-clipboard"></i>
                            {{total_signed_ups}} / {{event.signed_up.count}}
                        </strong> approved sign ups.
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 card mb-4 mt-3">
            <h4>Approved participants:</h4>
            <div class="card-body">
                <!-- Iterate through each sign_up in signed_up -->
                {% for sign in signed_up %}
                <div class="sign-p">
                    <!-- Full name -->
                    <strong>{{sign.first_name}} {{sign.last_name}}</strong>
                    <!-- Start number of the rider -->
                    #<strong>{{ sign.start_number }}</strong>
                    <!-- Username and signed up date. -->
                    - signed up by <i>{{sign.name}} - {{sign.created_on}}</i>

                    {% if user.is_authenticated and user.username == sign.name %}
                    <!-- Edit link -->
                    <span>
                        <a href="{% url 'edit_signup' slug=event.slug signup_id=sign.id %}" class="btn btn-link btn-sm">
                            <i class="fas fa-edit"></i>
                        </a>
                    </span>
                    <!-- Form to handle deletion of sign up -->
                    <form class="d-inline" action="{% url 'delete_signup' event.slug sign.id %}" method="post"
                        id="delete-form-{{ sign.id }}">
                        {% csrf_token %}
                        <button type="button" class="btn btn-link btn-sm text-danger"
                            onclick="showConfirmation('{{ sign.id }}')">
                            <i class="fa fa-trash"></i>
                        </button>
                        <span id="confirmation-text-{{ sign.id }}" class="confirm-delete btn btn-confirm btn-lg"
                            onclick="confirmDelete('{{ sign.id }}')">Confirm
                            delete!</span>
                    </form>

                    {% endif %}
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-4 card mb-4 mt-3 ">
            <div class="card-body">

                <!-- Sign up form -->
                {% if signed %}
                <div class="alert-two alert-success" role="alert">
                    Your sign up is awaiting confirmation.
                </div>
                {% else %}
                {% if user.is_authenticated %}
                {% if event.event_date|date:"Y-m-d" >= today %}
                <h4>Sign up to the event:</h4>
                <p>Signing up as: <strong>{{user.username}}</strong></p>
                <form method="post" style="margin-top: 1.3em;">
                    {{sign_up_form | crispy}}
                    {% csrf_token %}
                    <small id="start-number-alert" class="text-danger">
                    </small><br>
                    <button type="submit" class="btn btn-signup btn-lg">Submit</button>
                </form>
                {% else %}
                <div class="alert-two alert-warning" role="alert">
                    Sign up for this event has closed.
                </div>
                {% endif %}
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    // Handle check for existing start numbers in apporved sign ups.
    $(document).ready(function () {
        $('#id_start_number').on('change', function () {
            var enteredStartNumber = $(this).val();
            var existingStartNumbers = $(this).data('existing-start-numbers').split(',');
            var startNumberMessage = $('#start-number-alert');

            if (enteredStartNumber !== null && existingStartNumbers.includes(enteredStartNumber)) {
                startNumberMessage.text('This start number is already taken.');
                $(this).val('');
            } else {
                startNumberMessage.text('');
            }
        });
    });

    function confirmDelete(signupId) {
        var confirmationText = document.getElementById('confirmation-text-' + signupId);

        // Submit the form
        document.getElementById('delete-form-' + signupId).submit();
    }

    function showConfirmation(signupId) {
        var confirmationText = document.getElementById('confirmation-text-' + signupId);

        // Show visibility of the confirmation text
        confirmationText.style.display = confirmationText.style.display === 'inline' ? 'none' : 'inline';
    }
</script>
{% endblock content %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="container-fluid">
    <div class="row">
        <!-- Event Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for event in event_list %}
                    <div class="col-md-4">
                        <div class="card mb-4">
                            <div class="card-body">
                                <div class="image-container">
                                    <a href="{% url 'event_detail' event.slug %}">
                                        {% if "placeholder" in event.featured_image.url %}
                                            <img class="card-img-top" src="{% static 'images/emx.webp' %}" alt="Dirtbike rider revving away">
                                        {% else %}
                                            <img class="card-img-top" src="{{ event.featured_image.url }}" alt="Uploaded image for the event">
                                        {% endif %}
                                        <div class="image-flash-author">
                                            <p class="author">By: {{ event.author }}</p>
                                        </div>
                                        <div class="image-flash-event-date">
                                            <p class="author">{{ event.event_date }}</p>
                                        </div>
                                    </a>
                                </div>
                                <a href="{% url 'event_detail' event.slug %}" class="post-link">
                                    <h2 class="card-title">{{ event.title }}</h2>
                                    <p class="card-text">{{ event.excerpt | safe }}</p>
                                </a>
                                <hr>
                                <p class="card-text">{{ event.created_on }} <i class="far fa-heart"></i>
                                    {{ event.number_of_likes }} | 
                                    <strong class="text-secondary"><i class="far fa-clipboard"></i> {{ event.signed_up.count }}</strong>
                                </p>
                            </div>
                        </div>
                    </div>
                    {% if forloop.counter|divisibleby:3 %}
                    </div>
                    <div class="row">
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>

    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
{%endblock%}

templates/old_events.html
{% extends "base.html" %}
{% load static %}
{% block content %}

{% now "Y-m-d" as today %}

<div class="container-fluid">
    <div class="row">

        <!-- Event Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for event in event_list %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                <a href="{% url 'event_detail' event.slug %}">
                                    {% if "placeholder" in event.featured_image.url %}
                                    <img class="card-img-top" src="{% static 'images/emx.webp' %}"
                                        alt="dirtbike rider revving away">
                                    {% else %}
                                    <img class="card-img-top" src=" {{ event.featured_image.url }}"
                                        alt="Uploaded image for the event">
                                    {% endif %}
                                    <div class="image-flash-author">
                                        <p class="author">By: {{ event.author }}</p>
                                    </div>
                                    <div class="image-flash-event-date">
                                        <p class="author">{{ event.event_date }}</p>
                                    </div>
                                </a>
                            </div>
                            <a href="{% url 'event_detail' event.slug %}" class="post-link">
                                <h2 class="card-title">{{ event.title }}</h2>
                                <p class="card-text">{{ event.excerpt | safe }}</p>
                            </a>
                            <hr>
                            <!-- Show likes and signed ups -->
                            <p class="card-text text-muted h6">{{ event.created_on }} <i class="far fa-heart"></i>
                                {{ event.number_of_likes }} |
                                <strong class="text-secondary"><i class="far fa-clipboard"></i> {{ event.signed_up.count }}</strong>
                            </p>
                        </div>
                    </div>
                </div>

                {% endfor %}

            </div>
        </div>
    </div>
</div>
{%endblock%}